services:
  postgres:
    image: postgres:16-alpine
    container_name: mahiro-postgres
    environment:
      POSTGRES_USER: mahiro
      POSTGRES_PASSWORD: mahiro
      POSTGRES_DB: mahiro
    ports:
      - "5432:5432"
    volumes:
      - mahiro_pg_data:/var/lib/postgresql/data

  redis:
    image: redis:7-alpine
    container_name: mahiro-redis
    ports:
      - "6379:6379"

volumes:
  mahiro_pg_data: