"""Initial schema: stocks, snapshots, personas, holdings, watchlists

Revision ID: 822ca7310047
Revises: 
Create Date: 2026-05-27 19:04:28.547921

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '822ca7310047'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('personas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('style', sa.String(length=50), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_personas_id'), 'personas', ['id'], unique=False)
    op.create_index(op.f('ix_personas_name'), 'personas', ['name'], unique=False)
    op.create_index(op.f('ix_personas_owner'), 'personas', ['owner'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ticker', sa.String(length=20), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=True),
    sa.Column('sector', sa.String(length=100), nullable=True),
    sa.Column('industry', sa.String(length=100), nullable=True),
    sa.Column('market_cap_cr', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_stocks_id'), 'stocks', ['id'], unique=False)
    op.create_index(op.f('ix_stocks_ticker'), 'stocks', ['ticker'], unique=True)
    op.create_table('watchlists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('stock_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_watchlists_id'), 'watchlists', ['id'], unique=False)
    op.create_index(op.f('ix_watchlists_owner'), 'watchlists', ['owner'], unique=False)
    op.create_table('fundamental_snapshots',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('pe_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('pb_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('roe_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('debt_to_equity', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('revenue_growth_yoy_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('profit_margin_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('eps', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('eps_growth_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('working_capital_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('quick_ratio', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('debtor_days', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('public_holding_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('dividend_yield_pct', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('cash_flow_positive', sa.Boolean(), nullable=True),
    sa.Column('source', sa.String(length=50), nullable=False),
    sa.Column('raw_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('fetched_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_fundamental_snapshots_fetched_at'), 'fundamental_snapshots', ['fetched_at'], unique=False)
    op.create_index(op.f('ix_fundamental_snapshots_id'), 'fundamental_snapshots', ['id'], unique=False)
    op.create_index(op.f('ix_fundamental_snapshots_stock_id'), 'fundamental_snapshots', ['stock_id'], unique=False)
    op.create_table('holdings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('stock_id', sa.Integer(), nullable=False),
    sa.Column('owner', sa.String(length=100), nullable=False),
    sa.Column('quantity', sa.Numeric(precision=15, scale=4), nullable=False),
    sa.Column('avg_buy_price', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['stock_id'], ['stocks.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_holdings_id'), 'holdings', ['id'], unique=False)
    op.create_index(op.f('ix_holdings_owner'), 'holdings', ['owner'], unique=False)
    op.create_index(op.f('ix_holdings_stock_id'), 'holdings', ['stock_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_holdings_stock_id'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_owner'), table_name='holdings')
    op.drop_index(op.f('ix_holdings_id'), table_name='holdings')
    op.drop_table('holdings')
    op.drop_index(op.f('ix_fundamental_snapshots_stock_id'), table_name='fundamental_snapshots')
    op.drop_index(op.f('ix_fundamental_snapshots_id'), table_name='fundamental_snapshots')
    op.drop_index(op.f('ix_fundamental_snapshots_fetched_at'), table_name='fundamental_snapshots')
    op.drop_table('fundamental_snapshots')
    op.drop_index(op.f('ix_watchlists_owner'), table_name='watchlists')
    op.drop_index(op.f('ix_watchlists_id'), table_name='watchlists')
    op.drop_table('watchlists')
    op.drop_index(op.f('ix_stocks_ticker'), table_name='stocks')
    op.drop_index(op.f('ix_stocks_id'), table_name='stocks')
    op.drop_table('stocks')
    op.drop_index(op.f('ix_personas_owner'), table_name='personas')
    op.drop_index(op.f('ix_personas_name'), table_name='personas')
    op.drop_index(op.f('ix_personas_id'), table_name='personas')
    op.drop_table('personas')
    # ### end Alembic commands ###
