"""Add avg_volume_10d to fundamental_snapshots

Revision ID: d0bf853e7a34
Revises: 822ca7310047
Create Date: 2026-05-27 22:59:28.434476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd0bf853e7a34'
down_revision: Union[str, None] = '822ca7310047'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('fundamental_snapshots', sa.Column('avg_volume_10d', sa.Numeric(precision=15, scale=0), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('fundamental_snapshots', 'avg_volume_10d')
    # ### end Alembic commands ###
